version: '3.8'
services:
  # Remote Containers で開発したかったけど重すぎたのでコメントアウト
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.app
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - .:/app:cached
  #     - node_modules:/app/node_modules
  db:
    image: postgres:14
    restart: always
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  postgres:
  node_modules:
